// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SNCFDatabase.Data;
using System;

namespace SNCFDatabase.Migrations
{
    [DbContext(typeof(SNCFContext))]
    [Migration("20180509093840_AddAllForeignKeys")]
    partial class AddAllForeignKeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SNCFDatabase.Models.City", b =>
                {
                    b.Property<string>("ID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("SNCFDatabase.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("Date");

                    b.Property<int>("ForumID");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("ForumID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("SNCFDatabase.Models.Forum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Forum");
                });

            modelBuilder.Entity("SNCFDatabase.Models.Mark", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CommentID");

                    b.Property<DateTime>("Date");

                    b.Property<int>("UserID");

                    b.Property<float>("Value");

                    b.HasKey("ID");

                    b.HasIndex("CommentID");

                    b.ToTable("Mark");
                });

            modelBuilder.Entity("SNCFDatabase.Models.Opinion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityID");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<float>("Mark");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Opinion");
                });

            modelBuilder.Entity("SNCFDatabase.Models.Comment", b =>
                {
                    b.HasOne("SNCFDatabase.Models.Forum", "Forum")
                        .WithMany()
                        .HasForeignKey("ForumID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SNCFDatabase.Models.Forum", b =>
                {
                    b.HasOne("SNCFDatabase.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID");
                });

            modelBuilder.Entity("SNCFDatabase.Models.Mark", b =>
                {
                    b.HasOne("SNCFDatabase.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SNCFDatabase.Models.Opinion", b =>
                {
                    b.HasOne("SNCFDatabase.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID");
                });
#pragma warning restore 612, 618
        }
    }
}
