// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SNCFDatabase.Data;
using System;

namespace SNCFDatabase.Migrations
{
    [DbContext(typeof(SNCFContext))]
    partial class SNCFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SNCFDatabase.Models.City", b =>
                {
                    b.Property<string>("ID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("SNCFDatabase.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("Date");

                    b.Property<int>("ForumID");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("SNCFDatabase.Models.Forum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Forum");
                });

            modelBuilder.Entity("SNCFDatabase.Models.Mark", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CommentID");

                    b.Property<DateTime>("Date");

                    b.Property<int>("UserID");

                    b.Property<float>("Value");

                    b.HasKey("ID");

                    b.ToTable("Mark");
                });

            modelBuilder.Entity("SNCFDatabase.Models.Opinion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityID");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<float>("Mark");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Opinion");
                });
#pragma warning restore 612, 618
        }
    }
}
